<a href="https://colab.research.google.com/github/aditi150/SnakeGame/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import learning_curve
import warnings
warnings.filterwarnings('ignore')

In [54]:
dataset = pd.read_csv('/content/uci_dataset.csv')
dataset.head()

   144552912  9.3498486  56.7408757  17.05277157
0  144552912   9.350188   56.740679    17.614840
1  144552912   9.350549   56.740544    18.083536
2  144552912   9.350806   56.740485    18.279465
3  144552912   9.351053   56.740486    18.422974
4  144552912   9.351475   56.740502    19.124889

In [55]:
dataset.shape

(434873, 4)

In [56]:
dataset.isnull().sum()

144552912      0
9.3498486      0
56.7408757     0
17.05277157    0
dtype: int64

In [58]:
dataset = dataset.drop(['144552912'],axis=1)

In [ ]:
sns.countplot(x = '9.3498486', data=dataset)

In [47]:
X = dataset.iloc[:,0:-1]
y = dataset['9.3498486']

In [53]:
ss = StandardScaler()
ss.fit_transform(X)

ValueError: ignored

In [12]:
samples = []
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=i)
    samples.append((X_train, X_test, y_train, y_test))

In [13]:
samples

[(        144552912  9.3498486  56.7408757
  258685  144313644   8.362287   56.743928
  160781  103163358   9.272580   56.855249
  225045  152605357  10.417185   57.457602
  3393     23075889  10.502329   57.445262
  109516   38026941   9.868709   57.508292
  ...           ...        ...         ...
  122579   38050156   9.625442   57.282705
  304137   96187459  10.051241   57.007115
  152315  144038360  10.122457   56.906827
  117952   95712399   9.921597   57.320714
  305711   95140983   9.815592   57.282707

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  169989  115768906  10.337101   57.031937
  135439  117147132  10.195921   57.398428
  195882  146239742  10.251950   57.351864
  226588  106469850   9.971426   57.018857
  223323   93879858  10.032706   57.104141
  ...           ...        ...         ...
  11046    44069376   9.993745   57.025409
  138265  107297561  10.472440   57.473886
  124008   97740490  10.285054   57.160619
  155721   44432004  11.161800   57.318085
  160139   93725266   9.867506   57.450249

  [93901 rows x 3 columns],
  258685     8.362287
  160781     9.272580
  225045    10.417185
  3393      10.502329
  109516     9.868709
              ...
  122579     9.625442
  304137    10.051241
  152315    10.122457
  117952     9.921597
  305711     9.815592
  Name: 9.3498486, Length: 219101, dtype: float64,
  169989    10.337101
  135439    10.195921
  195882    10.251950
  226588     9.971426
  223323    10.032706
              ...
  11046      9.993745
  138265    10.472440
  124008    10.285054
  155721    11.161800
  160139     9.867506
  Name: 9.3498486, Length: 93901, dtype: float64),
 (        144552912  9.3498486  56.7408757
  116198   98853862  10.370578   57.591742
  186214   98643439  10.513947   57.345365
  3572    147857905   9.897589   57.037725
  243995  126452757   9.837578   56.722293
  122114  112498519   9.568984   56.684812
  ...           ...        ...         ...
  117583   48525045   9.644967   56.617485
  73349    92469054   9.956440   57.045943
  312201    8169311  10.467245   57.354778
  267336   22698747  10.519586   57.461095
  128037   98882659   9.070887   57.144781

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  188060  107382281  10.480509   57.482265
  242784   97089400   8.736344   56.619645
  44023    93169049  10.003285   57.453810
  242043   94989704  10.015550   57.482867
  234357   61409534   9.905353   56.798484
  ...           ...        ...         ...
  290580  102445905   9.375640   56.787834
  75020   115026978  10.028018   56.932958
  202289  103263437   9.898310   57.035611
  29530   114378249  10.268580   57.500827
  17986   103856547   8.442063   56.976178

  [93901 rows x 3 columns],
  116198    10.370578
  186214    10.513947
  3572       9.897589
  243995     9.837578
  122114     9.568984
              ...
  117583     9.644967
  73349      9.956440
  312201    10.467245
  267336    10.519586
  128037     9.070887
  Name: 9.3498486, Length: 219101, dtype: float64,
  188060    10.480509
  242784     8.736344
  44023     10.003285
  242043    10.015550
  234357     9.905353
              ...
  290580     9.375640
  75020     10.028018
  202289     9.898310
  29530     10.268580
  17986      8.442063
  Name: 9.3498486, Length: 93901, dtype: float64),
 (        144552912  9.3498486  56.7408757
  50429   121773077  10.327462   57.150528
  94837   101956144  10.065354   56.818260
  265096   97143529   9.725169   57.166765
  309944   98292300   9.961073   57.262092
  2710     95425632  10.279916   57.414432
  ...           ...        ...         ...
  33867   104524188   9.539190   56.869225
  84434   128145788   9.452559   56.975468
  95816   120832595   9.036564   56.844922
  203245  107459769  10.429559   57.399370
  100879  150204160  10.290734   56.766787

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  15691   133210917   8.489027   56.887329
  180264   70091660   8.292924   56.816476
  141780  104161120   9.265841   56.857637
  205832   26823651   8.850075   56.730675
  137774   96001640  10.041777   56.843746
  ...           ...        ...         ...
  44881    96315060   8.602449   57.118055
  252666   44684718   8.887367   56.633599
  194227   72607132   8.506691   56.931612
  53474   146945678  10.107555   57.004773
  169159  108427161   9.204976   56.836233

  [93901 rows x 3 columns],
  50429     10.327462
  94837     10.065354
  265096     9.725169
  309944     9.961073
  2710      10.279916
              ...
  33867      9.539190
  84434      9.452559
  95816      9.036564
  203245    10.429559
  100879    10.290734
  Name: 9.3498486, Length: 219101, dtype: float64,
  15691      8.489027
  180264     8.292924
  141780     9.265841
  205832     8.850075
  137774    10.041777
              ...
  44881      8.602449
  252666     8.887367
  194227     8.506691
  53474     10.107555
  169159     9.204976
  Name: 9.3498486, Length: 93901, dtype: float64),
 (        144552912  9.3498486  56.7408757
  151867   94754985   9.872279   57.011009
  293755  130764018   8.687331   56.752376
  230621   23646902  10.213851   57.214964
  233714  105446348   9.573238   56.886962
  278517   25868506  10.500776   57.496245
  ...           ...        ...         ...
  11261    37778629   9.951455   57.020798
  48056   144835526  10.454923   57.675519
  77049   100867697   8.620545   56.647884
  198296  149391542   9.827467   56.991213
  71530   126017585   9.546076   57.182613

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  38406   112306485  10.113322   56.957235
  276974   39497075   9.658456   57.306349
  299792   25991121   9.986866   57.443995
  189967  104280297   9.797776   56.643598
  277840   25867114  10.415609   57.499438
  ...           ...        ...         ...
  130223  136637175   9.874521   56.999958
  206961   99077459  10.122410   56.834753
  95360   119783093  10.225836   57.436866
  251589   47828875   9.855430   56.967813
  21069    98626344   8.657930   56.946804

  [93901 rows x 3 columns],
  151867     9.872279
  293755     8.687331
  230621    10.213851
  233714     9.573238
  278517    10.500776
              ...
  11261      9.951455
  48056     10.454923
  77049      8.620545
  198296     9.827467
  71530      9.546076
  Name: 9.3498486, Length: 219101, dtype: float64,
  38406     10.113322
  276974     9.658456
  299792     9.986866
  189967     9.797776
  277840    10.415609
              ...
  130223     9.874521
  206961    10.122410
  95360     10.225836
  251589     9.855430
  21069      8.657930
  Name: 9.3498486, Length: 93901, dtype: float64),
 (        144552912  9.3498486  56.7408757
  131373  143981794   8.230713   56.777473
  284982  124454910   8.682032   56.984349
  193125  152523555  10.144903   57.353820
  111746  129256637   9.638246   56.859975
  210987   26736429   9.820231   56.879661
  ...           ...        ...         ...
  107578   48509663   9.591297   57.250476
  94601   116635081  10.209324   57.512849
  115144  131358199  10.395722   57.584033
  129384  121955023   8.784913   56.640217
  120705   99913191   8.789848   56.972824

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  34626    26314613   9.996585   56.996383
  131081  109378039   8.867002   56.928944
  60589   121796784  10.128530   57.310533
  274247  124424078   8.659273   56.944326
  66500    40020279   9.025336   57.157196
  ...           ...        ...         ...
  211928   25750662   9.787803   57.129407
  176463   95143927   9.855943   56.764782
  775     125830887  10.138836   56.637091
  129953  137685147   9.281118   56.622526
  210614  107943167   9.780558   57.141313

  [93901 rows x 3 columns],
  131373     8.230713
  284982     8.682032
  193125    10.144903
  111746     9.638246
  210987     9.820231
              ...
  107578     9.591297
  94601     10.209324
  115144    10.395722
  129384     8.784913
  120705     8.789848
  Name: 9.3498486, Length: 219101, dtype: float64,
  34626      9.996585
  131081     8.867002
  60589     10.128530
  274247     8.659273
  66500      9.025336
              ...
  211928     9.787803
  176463     9.855943
  775       10.138836
  129953     9.281118
  210614     9.780558
  Name: 9.3498486, Length: 93901, dtype: float64),
 (        144552912  9.3498486  56.7408757
  54098   118634988   9.674073   57.144626
  172508  109483503   9.338140   56.717592
  148772   95133312  10.011828   57.350122
  37674   111141680  10.503296   57.414736
  225052   52990638   9.754204   57.406885
  ...           ...        ...         ...
  232422   25750636   9.576761   57.154848
  124605  149205570   9.940760   57.332741
  20463   156295933   9.790534   57.128170
  18638   154190663  10.116627   57.570942
  297827   39550401   9.923536   57.029801

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  230010   27837858   9.503735   56.625011
  15576   133210051   8.463532   56.850655
  231787  110681929   9.558877   56.701537
  41757   100782746   9.368821   57.054892
  275066  126527869   8.176500   56.630902
  ...           ...        ...         ...
  167846  105277030   9.632939   56.971615
  243467   10059637   9.886458   57.039914
  8034    114647899   9.344631   56.846249
  202619  103264009   9.888370   57.039442
  280149  121292114  10.373535   57.057563

  [93901 rows x 3 columns],
  54098      9.674073
  172508     9.338140
  148772    10.011828
  37674     10.503296
  225052     9.754204
              ...
  232422     9.576761
  124605     9.940760
  20463      9.790534
  18638     10.116627
  297827     9.923536
  Name: 9.3498486, Length: 219101, dtype: float64,
  230010     9.503735
  15576      8.463532
  231787     9.558877
  41757      9.368821
  275066     8.176500
              ...
  167846     9.632939
  243467     9.886458
  8034       9.344631
  202619     9.888370
  280149    10.373535
  Name: 9.3498486, Length: 93901, dtype: float64),
 (        144552912  9.3498486  56.7408757
  11762   123762845   9.991424   57.455125
  154907  123072567   9.632777   56.736991
  255737  100266565   9.294638   56.705812
  4932    146812051  10.380406   57.200415
  246503   40474642  10.293380   56.609286
  ...           ...        ...         ...
  195949   69694233   8.153125   56.620689
  266858   99243102   8.359703   56.932386
  239572   30921058  10.107055   56.935077
  303331   89934579   9.799408   56.597610
  162698  151402213   9.770834   57.398420

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  113013    9720812   9.965180   57.039334
  260016  114579665   9.592513   57.245322
  144073   32390754   9.943880   57.081070
  253759  102868306  10.489252   57.209619
  69052   125684595   9.929644   56.755664
  ...           ...        ...         ...
  37424    95525669   9.970393   57.571664
  239845   32066409   9.907290   57.061448
  264439  107628386   9.644697   56.910068
  142367  131425001   9.813095   57.329514
  76634    96672305  10.586009   57.732494

  [93901 rows x 3 columns],
  11762      9.991424
  154907     9.632777
  255737     9.294638
  4932      10.380406
  246503    10.293380
              ...
  195949     8.153125
  266858     8.359703
  239572    10.107055
  303331     9.799408
  162698     9.770834
  Name: 9.3498486, Length: 219101, dtype: float64,
  113013     9.965180
  260016     9.592513
  144073     9.943880
  253759    10.489252
  69052      9.929644
              ...
  37424      9.970393
  239845     9.907290
  264439     9.644697
  142367     9.813095
  76634     10.586009
  Name: 9.3498486, Length: 93901, dtype: float64),
 (        144552912  9.3498486  56.7408757
  169748   27687738   9.894516   57.046473
  276750   39497056   9.666232   57.312988
  227697  150514147  10.273631   56.776302
  272013  103450605   8.792655   56.866676
  290635  146486123   9.899975   57.093887
  ...           ...        ...         ...
  235075  123278503  10.600028   57.725172
  10742   121663339  10.218593   57.008239
  49689   104993599   9.876810   57.005183
  189636   28782435  10.198681   56.885680
  61615   115507531   9.559307   57.231160

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  142721  108356687  10.263559   57.239330
  296972  139161027  10.068167   57.131777
  48681   128058745   9.960222   57.297615
  88991    23298189  10.498275   57.433375
  308978   95143930   9.862171   56.774680
  ...           ...        ...         ...
  7656    102780759   8.418320   56.748033
  75136   100862376   9.034556   56.590535
  146950   97886640   9.899631   56.846951
  83117    95637369   9.977125   57.572122
  52536   103953309   8.351557   56.869314

  [93901 rows x 3 columns],
  169748     9.894516
  276750     9.666232
  227697    10.273631
  272013     8.792655
  290635     9.899975
              ...
  235075    10.600028
  10742     10.218593
  49689      9.876810
  189636    10.198681
  61615      9.559307
  Name: 9.3498486, Length: 219101, dtype: float64,
  142721    10.263559
  296972    10.068167
  48681      9.960222
  88991     10.498275
  308978     9.862171
              ...
  7656       8.418320
  75136      9.034556
  146950     9.899631
  83117      9.977125
  52536      8.351557
  Name: 9.3498486, Length: 93901, dtype: float64),
 (        144552912  9.3498486  56.7408757
  181888  107406655  10.488655   57.471673
  55133    71452344   9.914510   57.044214
  10917    44069326   9.996411   57.024915
  60301    42104268   9.808865   56.591023
  304817   99334212   8.571863   57.019477
  ...           ...        ...         ...
  231557  110681652   9.561847   56.694701
  256361  127530525   9.891119   57.015136
  149489   75874320  10.161236   57.208101
  25940    95495789  10.417600   57.570939
  70083   148034795  10.276793   57.125735

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  153207  141796723   9.941580   57.583780
  83152   128143244   9.472404   56.973685
  294884  149641232  10.931182   57.283235
  254858   97118920   9.967333   57.045811
  134687   37035263   9.473890   57.071016
  ...           ...        ...         ...
  241716   97085509  10.433923   57.612615
  115426  105144004   9.371188   56.907218
  157515   55971439   9.945881   57.046712
  144448   89487858   9.854931   56.851109
  292178  149634998  10.990619   57.261909

  [93901 rows x 3 columns],
  181888    10.488655
  55133      9.914510
  10917      9.996411
  60301      9.808865
  304817     8.571863
              ...
  231557     9.561847
  256361     9.891119
  149489    10.161236
  25940     10.417600
  70083     10.276793
  Name: 9.3498486, Length: 219101, dtype: float64,
  153207     9.941580
  83152      9.472404
  294884    10.931182
  254858     9.967333
  134687     9.473890
              ...
  241716    10.433923
  115426     9.371188
  157515     9.945881
  144448     9.854931
  292178    10.990619
  Name: 9.3498486, Length: 93901, dtype: float64),
 (        144552912  9.3498486  56.7408757
  125888  126302094   9.894046   56.693643
  81722    26427531   9.657580   56.994254
  143280   41128561   8.191008   56.593074
  24676   102832262   8.367288   56.748308
  189282   74918888   9.812657   57.484787
  ...           ...        ...         ...
  91261    25729339   9.460681   57.139239
  267158  151632307  10.116997   57.359414
  173819  139894128  10.449768   57.415131
  196534  132609599   8.305927   56.815398
  187006   28777265  10.261703   57.155418

  [219101 rows x 3 columns],
          144552912  9.3498486  56.7408757
  298402  152797779  10.433202   57.484798
  22482   141622603   9.836502   57.443317
  110737  114574876   9.596800   57.260930
  290974   69940623   9.919601   57.550422
  75694   132322087   9.583845   57.244080
  ...           ...        ...         ...
  171920  151425282   9.860922   56.625156
  134254   25499344   9.893780   56.919705
  58807   115502275   9.430990   56.684464
  142665  110453774  10.936647   57.297119
  194059   96952343  10.909191   57.268847

  [93901 rows x 3 columns],
  125888     9.894046
  81722      9.657580
  143280     8.191008
  24676      8.367288
  189282     9.812657
              ...
  91261      9.460681
  267158    10.116997
  173819    10.449768
  196534     8.305927
  187006    10.261703
  Name: 9.3498486, Length: 219101, dtype: float64,
  298402    10.433202
  22482      9.836502
  110737     9.596800
  290974     9.919601
  75694      9.583845
              ...
  171920     9.860922
  134254     9.893780
  58807      9.430990
  142665    10.936647
  194059    10.909191
  Name: 9.3498486, Length: 93901, dtype: float64)]

In [14]:
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
result = pd.DataFrame(columns=['Sample', 'Best Accuracy', 'Best Kernel', 'Best Nu', 'Best Epsilon'])

In [15]:
def fitnessFunction(kernel, C, gamma):
  svm = SVC(kernel=kernel, C=C, gamma=gamma, max_iter=1000)
  svm.fit(X_train, y_train)
  y_pred = svm.predict(X_test)
  return accuracy_score(y_pred, y_test)

In [24]:
X = X.dropna()

In [26]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

In [30]:
for i in range(len(samples)):
  best_accuracy = 0
  best_C = 0
  best_gamma = 0
  for kernel in kernels:
    X_train, X_test, y_train, y_test = samples[i]
    C = np.random.uniform(0, 10)
    gamma = np.random.uniform(0, 10)
    score = fitnessFunction(kernel, C, gamma)
    if score>best_accuracy:
      best_accuracy = round(score, 2)
      best_C = round(C, 2)
      best_gamma = round(gamma, 2)
      best_kernel = kernel
  print('Best Accuracy = ', best_accuracy, 'Best Kernel = ', best_kernel, 'Best Nu = ', best_C, 'Best Epsilon = ', best_gamma)
  result.loc[i] = [i+1, best_accuracy, best_kernel, best_C, best_gamma]

ValueError: ignored

In [19]:
result

Empty DataFrame
Columns: [Sample, Best Accuracy, Best Kernel, Best Nu, Best Epsilon]
Index: []

In [20]:
X_train, X_test, y_train, y_test = samples[result['Best Accuracy'].idxmax()]

TypeError: ignored

In [31]:

train_sizes, train_scores, test_scores = learning_curve(SVC(kernel=result['Best Kernel'].iloc[result['Best Accuracy'].idxmax()], 
                                                        C=result['Best Nu'].iloc[result['Best Accuracy'].idxmax()],
                                                        gamma=result['Best Epsilon'].iloc[result['Best Accuracy'].idxmax()],
                                                        max_iter = 1000), X_train, y_train, cv=10, scoring='accuracy', n_jobs=-1,
                                                        train_sizes = np.linspace(0.01, 1.0, 50))

TypeError: ignored